### ISSUE TITLE
Feature Inquiry: Garage Door Opener Light

### ISSUE THREAD

**Issue by donavanbecker** [iRayanKhan/homebridge-chamberlain#81] opened 2020-01-20 17:32 UTC
# Explain the feature you want added
(Give a description of the feature you want added.)

I am guessing not, but figured i would ask. Is there a way to control the light on the garage door opener? or are chamberlain openers not made that way?

**Comment by iRayanKhan** [comment] 2020-01-21 15:28
Duplicate of #78, but I am looking into it right now and have some work done. If you get extra device ID's for your garage door, then it will work (not ethernet gateway), but the chamberlain light controller kit is what I'm tryna get to work along with door locks.

**Closed as completed by iRayanKhan** 2020-01-21 15:28 UTC
Labels: featureRequest
