### ISSUE TITLE
error loading plugin.. on clean homebridge install 

### ISSUE THREAD

**Issue by imaredia** [iRayanKhan/homebridge-chamberlain#22] opened 2017-08-03 16:09 UTC
I am getting this error,

`[8/3/2017, 11:01:30 AM] ====================
[8/3/2017, 11:01:30 AM] ERROR LOADING PLUGIN homebridge-chamberlain:
[8/3/2017, 11:01:30 AM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-chamberlain/src/index.js:1:92)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
[8/3/2017, 11:01:30 AM] ====================
`
node version ver 4.2.6
homebridge ver 0.4.22
npm ver 3.5.2
on ubuntu server 16.04

**Comment by caseywebdev** [comment] 2017-08-03 18:47
Duplicate of #2

**Closed as completed by caseywebdev** 2017-08-03 18:47 UTC
