### ISSUE TITLE
Multiple Garage Doors to Open/Close

### ISSUE THREAD

**Issue by grabidou** [iRayanKhan/homebridge-chamberlain#12] opened 2016-12-10 18:46 UTC
I was finally able to get both garage doors opening and closing with the deviceId.  Is there any way to close/open them both at the same time?  It seems i have to do them both individually.  Maybe a new accessory in the config.json to include both deviceid's?  Has anyone done this?

**Comment by caseywebdev** [comment] 2016-12-11 15:15
Have you tried something like "Hey Siri open the garage doors"? It looks like the Home app won't let you group garage doors like it will with lights, which is kinda annoying. It seems like it would be possible to treat the two doors as one accessory and just make two API calls to the chamberlain servers for every action. There is the possibility that one call succeeds and the other fails though which would result in a wonky state.

**Comment by grabidou** [comment] 2016-12-12 15:39
Yah, Tried a couple of phrases with Siri, including "Siri, Close all garage doors", "Siri, Open all garage doors", "Siri, Open both garage doors", etc...  No luck.  The other thing i noticed, there has to be a pause before closing the second door (Even with the app).  Seems that chamberlain gets confused, or just doesn't know how to handle it.

**Comment by caseywebdev** [comment] 2016-12-12 17:00
You'd think given how common multiple doors are Chamberlain would have a way of linking 2 openers to each other. The pause may be some sort of rate limit with their API, probably intended to prevent accidental double clicks or something like that.

**Comment by gonzal40** [comment] 2016-12-27 13:59
I have both of my Chamberlain hd950wf openers working with Siri. I use "Hey, Siri. Open / close the garage doors." Saying "open / close both garage doors" works as well. Both openers are defined as individual accessories in my config file. They both use the same Chamberlain account credentials to authenticate, but are differentiated by their device ID numbers.

**Comment by scotteby** [comment] 2017-02-17 18:58
I can confirm I have the same issue when trying to open or close both openers at the same time. I created a scene in the Home app that sets them both to open and it throws an error in the api when I test the scene.

 I suppose a timing issue on their server is possible, however I will say that I just switched from the homebridge-liftmaster plugin to this one and I didn't have this issue on the old plugin. Their api got shut down this week so I'm at least glad this plugin has the basic functionality working.

I wrote a separate node app that sets the status to open on each one and it works fine so I'm not sure what the difference is.

```
garageDoor.setDeviceAttribute({name: 'desireddoorstate', value:1})
      .then(() => {
        console.log("main gate open");	
      });
	  
garageDoor2.setDeviceAttribute({name: 'desireddoorstate', value:1})
      .then(() => {
        console.log("side gate open");	
      });
```

**Comment by caseywebdev** [comment] 2017-02-17 19:12
I only have one garage door so I'm afraid I won't be able to help debug this.

**Comment by ndobbs** [comment] 2017-02-23 17:32
I just purchased 2x Chamberlain WD1000WF, I'm curious to see if I will run into this issue. I'll check it out once I get everything online and working and report back.

**Comment by michaelagleason** [comment] 2017-04-16 02:54
In the Home app, if you define a room as "garage" and then assign both garage doors to it, that should accomplish what you are looking for. I did that and was able to say "Open garage" or "Close garage" and both doors opened and closed.

**Comment by grabidou** [comment] 2017-04-18 14:01
I just tried the close or open Garage command. The result was only one opened, and one closed. If I said the command twice, it was smart enough to know which one was already open and open the other door. Same with closing. Still no joy on getting them both to close at the same time or with one command.

**Comment by michaelagleason** [comment] 2017-04-19 00:58
In the Home App on your iOS device, you have the ability to define “rooms” and assign devices to those rooms. I created a room called “Garage” and assigned my home bridge and both garage doors to it (see image linked below). When I say “Open Garage”, Siri responds by opening both at the same time. When I say “Close Garage”, Siri responds by closing both doors at the same time. Have you defined a room?

![img_0122](https://cloud.githubusercontent.com/assets/27599753/25158911/e524068c-2479-11e7-8997-e203a85f3474.PNG)

**Comment by grabidou** [comment] 2017-04-21 21:34
Yes, I did create a room called "Garage"...  i've tried it a few times, and the doors open at random...

![img_4867](https://cloud.githubusercontent.com/assets/23324058/25296919/9242667a-26b8-11e7-85f8-2dcd1841330d.PNG)

**Comment by GvnCampbell** [comment] 2017-04-21 21:40
Give this a try. Try renaming the garage doors as a test. I named mine 'left Door' and 'right Door'. I then have them both in a garage room and command them by saying 'hey Siri open the left Door' or 'right door' or 'garage doors' and it works. 

I remember reading an article that mentioned that naming things was important as Siri may react differently. Hopefully that works.

**Comment by michaelagleason** [comment] 2017-04-21 21:55
The command I use is Open “Garage”

**Comment by chasebmcvicker** [comment] 2017-05-09 01:13
I have one garage door, but when I tried to add it as an accessory, i got the error message saying "Multiple controllable devices found".  This was followed by 6 device ID's.  How do I tell which one is my door?

**Comment by michaelagleason** [comment] 2017-05-09 06:24
One is for the door, the other seems to be the light mechanism. I showed 2 IDs so just put in one at a time to figure it out.

**Comment by iRayanKhan** [comment] 2019-10-21 20:54
Closed;
Inactive.

**Closed as completed by iRayanKhan** 2019-10-21 20:54 UTC
